### ISSUE TITLE
Is it possible to send log from hapi-pino to elasticsearch

### ISSUE THREAD

**Issue by lioaslan** [pinojs/hapi-pino#105]
Hi, I'm working on a project using `hapi-pino` for logging in json. 
I try to use `pino-elasticsearch` to ship log to elasticsearch but it don't work like I want.

-  `request.log([tags], data)`: Elasticsearch can get **first** tag, nothing else

- `request.logger.info/warn/error(message)`: Elasticsearch can't get this log type.

However, I use `pino` like example in `pino-elasticsearch` and it worked.
Thanks for any helps and sorry about my poor English :(

**Comment by mcollina** [comment]
@delvedor can you help?

**Comment by delvedor** [comment]
Hello! Which version of Elasticsearch are you using?
Can you add here the pino-elasticsearch configuration and your index mappings?

**Comment by lioaslan** [comment]
- I'm using Elasticsearch with 7.6.2 version
- Here is pino-elasticsearch configuration and integrate to hapi-pino:
```javascript
const streamToElastic = PinoElasticsearch({
    index: 'abc-api',
    type: 'log',
    consistency: 'one',
    node: 'http://elastic:changeme@localhost:9200',
    'es-version': "7.6.2",
    'bulk-size': 200,
    ecs: true
});

await server.register({
    plugin: HapiPino,
    options: {
        logPayload: true,
        prettyPrint: process.env.NODE_ENV !== 'production',
        redact: {
            paths: ['req.headers', 'payload.user.password', 'payload.file'],
            remove: true
        },
        stream: streamToElastic
    }
});
```
Thanks so much

**Comment by delvedor** [comment]
Can you also paste here the Elasticsearch index mapping? You can get it with the following command:
```
curl -u elastic:changeme localhost:9200/abc-api/_mapping
```

I would also recommend to not use the `ecs` option in `pino-elasticsearch`, but use [@elastic/ecs-pino-format](https://github.com/elastic/ecs-logging-js/tree/master/loggers/pino) instead.

**Comment by lioaslan** [comment]
Elasticsearch index mapping:
```json
{
   "offshorevn-api":{
      "mappings":{
         "properties":{
            "@timestamp":{
               "type":"date"
            },
            "ecs":{
               "properties":{
                  "version":{
                     "type":"text",
                     "fields":{
                        "keyword":{
                           "type":"keyword",
                           "ignore_above":256
                        }
                     }
                  }
               }
            },
            "pino":{
               "properties":{
                  "data":{
                     "type":"text",
                     "fields":{
                        "keyword":{
                           "type":"keyword",
                           "ignore_above":256
                        }
                     }
                  }
               }
            }
         }
      }
   }
}
```

**Comment by delvedor** [comment]
There is an error in your configuration, you set `'es-version'` to `'7.6.2'`.
It should be `7`, only the major version number.
Also, you don't need to configure the type, as it's no longer supported in Elasticsearch v7.

**Comment by lioaslan** [comment]
- I try fixing `'es-version'` and remove `type` but it still doesn't work.
- If I use `@elastic/ecs-pino-format`, how to config it with `hapi-pino`?

**Comment by delvedor** [comment]
> If I use @elastic/ecs-pino-format, how to config it with hapi-pino?

You should use Pino v6, then I think the following should work:
```js
const ecsFormat = require('@elastic/ecs-pino-format')()
await server.register({
    plugin: HapiPino,
    options: {
        ...ecsFormat,
        logPayload: true,
        prettyPrint: process.env.NODE_ENV !== 'production',
        redact: {
            paths: ['req.headers', 'payload.user.password', 'payload.file'],
            remove: true
        },
        stream: streamToElastic
    }
});
```

**Comment by lioaslan** [comment]
Thanks so much, it worked
I create an instance of Pino with elasticsearch stream and put it into hapi-pino config
```javascript
const streamToElastic = PinoElasticsearch({
    index: 'abc-api',
    consistency: 'one',
    node: 'http://elastic:changeme@localhost:9200',
    'bulk-size': 200,
    'es-version': 7
});

const logger = Pino({ level: "info" }, streamToElastic);

await server.register({
    plugin: HapiPino,
    options: {
        ...ecsFormat,
        logPayload: true,
        prettyPrint: process.env.NODE_ENV !== 'production',
        redact: {
            paths: ['req.headers', 'payload.user.password', 'payload.file'],
            remove: true
        },
        instance: logger,
        stream: streamToElastic,
        mergeHapiLogData: true
    }
});```
