### ISSUE TITLE
Usage example does not work

### ISSUE THREAD

**Issue by simon-lorenz** [pinojs/hapi-pino#106]
While trying hapi-pino for the first time, I found some Issues in the Usage example:

1. `const Hapi = require('hapi')` should be `const Hapi = require('@hapi/hapi')`
2. `plugin: require('.'),` didn't work for me, `plugin: require('hapi-pino'),` did
3. I don't know what `require('make-promises-safe')` is for, it seems to be not necessary and isn't explained.

Tested with hapi 19.1.1 and hapi-pino 8.0.1

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by simon-lorenz** [comment]
I sent a PR but I don't know how I would unit test a README file.
