### ISSUE TITLE
Convert log

### ISSUE THREAD

**Issue by lioaslan** [pinojs/hapi-pino#118]
Hi,
I'm using hapi-pino for logging but I don't know how I can map the field contain IP with location to new field (or overwrite IP field).
In other words, I want to customize log and maybe use middleware (for mapping IP to locaiton) on process,

### Current
```json
{
   "ip": "123.123.123.123"
}
```
### What I want
```json
{
   "ip": "123.123.123.123",  // May be removed
   "location": "USA"
}
```

Thanks

**Comment by mcollina** [comment]
See https://getpino.io/#/docs/api?id=formatters-object
