### ISSUE TITLE
Question: How to redact request payload field when logPayload = true

### ISSUE THREAD

**Issue by paulrobello** [pinojs/hapi-pino#126]
I tried something like below, however the password field is still logged when the json object is POSTed to the route.
POST BODY
{"username": "the man", "password":"secret"}

const loggerOptions: HapiPino.Options = {
    prettyPrint: process.env.NODE_ENV !== 'production',
    redact: ['req.headers.authorization', 'req.payload.password'],
    logPayload: true,
    logRouteTags: true,
    ignorePaths: ['/health'],
    level: 'debug'
  };

**Comment by mcollina** [comment]
the payload is logged as `payload`, not `req.payload`.
