### ISSUE TITLE
Redact paths doesn't allow hyphens

### ISSUE THREAD

**Issue by SeRodrigalvarez** [pinojs/hapi-pino#127]
I'm trying to redact a header field which has a hyphen:

```
const plugin = {
    plugin: require("hapi-pino"),
    options: {
        redact: {
            paths: [ "req.headers.authorization", "auth-token", "password", "token" ],
        },
    },
};

```
But i'm getting the following error:  `pino – redact paths array contains an invalid path (auth-token)`

**Comment by felix-adnymics** [comment]
Hi @SeRodrigalvarez 👋 

Hyphens are actually supported, just in a different way.
That's more obvious when we have look at the part of `fast-redact` that actually throws the error:
https://github.com/davidmarkclements/fast-redact/blob/master/lib/validator.js#L24-L32

![image](https://user-images.githubusercontent.com/70569061/104049206-dd2c6680-51e4-11eb-8bb4-365f98a71e07.png)

Based on the [docs](https://github.com/davidmarkclements/fast-redact#paths--array) I'd suggest something like:
```js
const plugin = {
    plugin: require("hapi-pino"),
    options: {
        redact: {
            paths: [ "req.headers.authorization", "['auth-token']", "password", "token" ],
        },
    },
};
```

Thus the evaluated code will look like `o['auth-token']` which is valid 😊

**Comment by felixheck** [comment]
Hi @SeRodrigalvarez 👋

Hyphens are actually supported, just in a different way.
That's more obvious when we have look at the part of fast-redact that actually throws the error:
https://github.com/davidmarkclements/fast-redact/blob/master/lib/validator.js#L24-L32

![image](https://user-images.githubusercontent.com/14093205/104049526-62178000-51e5-11eb-908a-2c4ea6fc6e11.png)

Based on the [docs](https://github.com/davidmarkclements/fast-redact#paths--array) I'd suggest something like:

```js 
const plugin = {
    plugin: require("hapi-pino"),
    options: {
        redact: {
            paths: [ "req.headers.authorization", "['auth-token']", "password", "token" ],
        },
    },
};
```
Thus the evaluated code will look like `o['auth-token']` which is valid 😊

**Comment by SeRodrigalvarez** [comment]
Hi @felixheck 

It works! Thanks for the quick response and explanation!
