### ISSUE TITLE
How to capture the request startTime in hapi-pino.

### ISSUE THREAD

**Issue by fcesgpfedef** [pinojs/hapi-pino#130]
We are getting responsetime in the log. If I can get the startTime of the request I can process the endtime by adding responsetime to start time.

Is there a parameter in options that I can enable to log request  startTime ?
Please give the example code snippet if available.. Thanks

**Comment by felixheck** [comment]
Hey!

The logged `responseTime` is calculated by `hapi-pino` based on three properties of the `request` object.

```js
responseTime: (info.completed !== undefined ? info.completed : info.responded) - info.received
```

As `req.info.completed` & `req.info.responded` (end time) and `req.info.received` (start time) are part of the logged `req` property, you should be able to access & log the end time using [a custom serializer](https://github.com/pinojs/hapi-pino#optionsserializers--key-string-pinoserializerfn-)

For more info, check the respective lines of code:
https://github.com/pinojs/hapi-pino/blob/master/index.js#L160-L172

**Comment by fcesgpfedef** [comment]
Hi,

Thanks so much for the prompt response. I tried with serializers but couldn't find any proper examples or documenttaion on how to use them. So used formatters and able to capture the req.info

```
formatters: {
    log(object) {
        const info = _.get(object, "req.info");
        if (info) {
            return {
                ...object,
                info,
            };
        }   else {
                return object;
        }
    }
},
```
