### ISSUE TITLE
Not able to set log level during runtime

### ISSUE THREAD

**Issue by midnightcodr** [pinojs/hapi-pino#132]
```
server.logger.level('debug')
```
failed with `unhandledRejection server.logger.level is not a function`, so it seems `logger` is not a vanilla instance of the Pino? Because logger.level exists in it. Any plan to add `.level()` call?

**Comment by mcollina** [comment]
I don't really use this module much anymore. I'll be happy to review a PR if you'd like to send one.

**Comment by midnightcodr** [comment]
Sure, here's one https://github.com/pinojs/hapi-pino/pull/133
