### ISSUE TITLE
Merge hapi log event data into pino serialized object.

### ISSUE THREAD

**Issue by juanjoLenero** [pinojs/hapi-pino#15]
I would like to stick to the hapi logging interface, but at the same time take advantage of the properties serialized by pino.

Current behaviour is this (hapi-pino 1.4.1):
```js
server.log(['error'], { err, msg: 'x went wrong' });

// Pino log
{ ... tags: ['error'], data: { err: err, msg: 'x went wrong' } }
```
But I would rather see:
```js
{ ... tags: ['error'], err: err, msg: 'x went wrong' }
```
In short, I would like to be able to merge Hapi log event data properties into pino's object root instead of under the `data` key.

edit: I would also like to see this:
```js
server.log(['info'], 'job completed');

// Current behaviour
{ ... tags: ['info'], data: 'job completed' }

// Wanted behaviour
{ ... tags: ['info'], msg: 'job completed' }
```

**Comment by davidmarkclements** [comment]
What about collisions? 

```js
server.log(['error'], {tags: 'oh oh'})
```

**Comment by juanjoLenero** [comment]
@davidmarkclements I think pino already explains that both keys would end up in the output, your example would result in:
```js
{ ... tags: ['error'], tags: 'oh oh' }
```
I don't think that would be a problem, since that's what is already expected of pino.

**Comment by davidmarkclements** [comment]
they would - but once parsed (say by an intermediate transform/transport/when stored in a db perhaps) the second `tags` would override the first

```
JSON.parse('{"a": 1, "a": 2}') // {a: 2}
```

**Comment by juanjoLenero** [comment]
That's what I would expect after reading pino's documentation. The concern here is that you could add an external hapi plugin that uses the log interface and inadvertently overwrites one of pino's main properties (`level`, `name`, ... etc) right? And I guess that would leave you no clean way of handling the conflict.

In my use case, none of the plugins I'm using do any logging. So I control all calls to hapi's logging interface. But I get your point, and I can't think of a good workaround.

**Comment by juanjoLenero** [comment]
This might be a bit hackish but what about explicitly opting in to the merging of the properties with a custom key and a boolean value.

E.g.
```js
// I'm aware of the pino backend to hapi's log interface and accept the risks:
server.log(['error'], { err, job, msg: 'job error', mergePino: true });

// In some third party module we have no control of:
server.log(['error', 'stats', 'report'], { level: 'ui', tags: 'performance, report' });
// No opt-in to merge property, so everything would end under the data key.
```
Would checking for the special property and doing the merge constitute a substantial performance hit?

**Comment by davidmarkclements** [comment]
Yeah no where else in pino do we allow for opt setting on a log object, and I think it would esoteric to do it here. 

@mcollina made the design choice, I think we've scrutinised a primary reason for it - perhaps there's more - @mcollina what's your thoughts?

**Comment by mcollina** [comment]
The reason for this is well described in https://github.com/pinojs/hapi-pino/issues/15#issuecomment-301856371.

However, I'm happy to reconsider and merge them.. if two things overlap, no big deal. Can we make this a plugin-level option? That would work well for this.

**Comment by juanjoLenero** [comment]
Sure, a plugin-level option would work. Just to be clear, that's a no-go on the opt-in key inside hapi's log data?

Also, the change seems trivial enough, I could open a PR if you like.

**Comment by mcollina** [comment]
> that's a no-go on the opt-in key inside hapi's log data?

Can you clarify?

**Comment by davidmarkclements** [comment]
@mcollina I believe @juanjoLenero is referring to not setting hapi-pino options through log message objects based on me saying "no where else in pino do we allow for opt setting on a log object" and you saying "Can we make this a plugin-level option?"

**Comment by juanjoLenero** [comment]
I'm refering to this: https://github.com/pinojs/hapi-pino/issues/15#issuecomment-301859212

Say we go with the plugin-level option.
```js
{
    register: 'hapi-pino',
    options: {
        mergeHapiLogData: true
    }
}
```
And now everything works as I detailed in the opening post of this thread.

Down the line I add a third party plugin say a server metrics reporter that uses Hapi's logging interface and is unaware that we are delegating to pino. 

If this new plugin were to include conflicting keys in a log event's data (e.g. level, name, etc...) then as @davidmarkclements  mentioned in https://github.com/pinojs/hapi-pino/issues/15#issuecomment-301852685 we would lose our original level/name.

I still think this would be a very exceptional case, which is why I wouldn't mind living with the conflict  if it ever arises.

**Comment by mcollina** [comment]
@juanjoLenero 👍

**Comment by mcollina** [comment]
would you mind sending a PR?

**Comment by juanjoLenero** [comment]
Not at all, I will implement it as a plugin-level option that toggles between merging the data or adding it under a `data` key (current behaviour).

**Comment by juanjoLenero** [comment]
PR is ready at https://github.com/pinojs/hapi-pino/pull/16.
