### ISSUE TITLE
Differ between `server.log` and `request.log` in `prettyPrint.formatter`

### ISSUE THREAD

**Issue by felixheck** [pinojs/hapi-pino#19]
Hey guys,

is it possible to detect if logs are created with `server.log` or with `request.log`?
Is it enough to check if the logged message contain a `req` property?

Thanks.

**Comment by mcollina** [comment]
Yes, I think the main difference would be a `req` property.

**Comment by felixheck** [comment]
I disable `mergeHapiLogData` so it might be enough..hmm..let's try 👍 
Thanks @mcollina
