### ISSUE TITLE
Support option for ignoring paths

### ISSUE THREAD

**Issue by deedubs** [pinojs/hapi-pino#26]
Our hapi servers export a `/healthz` it would be nice if we could omit those requests from the logs.

Would you be open to a PR for this functionality?

I know another option would be to pipe to a filter but I wanted to see the appetite for this built in.

**Comment by mcollina** [comment]
Definitely, you might want to use find-my-way to match the routes.

**Comment by davidmarkclements** [comment]
related: https://github.com/pinojs/pino-http/issues/40 (@mcollina - perhaps not implementation but the idea.. path ignoring)

**Comment by tiagoalves** [comment]
I need to silence our `/healthz` polling logs as well and tried to use the new `ignorePaths` feature in PR #30. However, it's not flexible enough for my use case since it matches the routes against `request.url.path` which includes the request's query params but my query params can have dynamic values.

Just in case it helps someone in the future, I ended up silencing our logs with this micro hapi plugin:

```
/**
 * A minimal plugin that silences the `hapi-pino`
 * response log for the `/healthz` route.
 */
exports.plugin = {
  register: async (server, options) => {
    server.ext('onPreResponse', (request, h) => {
      if (request.url.pathname === '/healthz') {
        request.logger.level = 'silent'
      }
      return h.continue
    })
  },
  name: 'health-log-silencer',
  version: '1.0.0'
}
```

**Comment by paulovieira** [comment]
The `ignorePaths` option is useful for sure (another typical use case would be paths relative to static files). But it could be a bit more useful if the path could be given with a wildcard. Exemple:
```
ignorePaths: ['/static*']
```

In this case the comparison could be done with `startsWith` instead of equality.

**Comment by muuhoffman** [comment]
I was still struggling with this and this worked well for me in the `pino-http` or `express-pino-logger` (which just uses `pino-http`) library:
```
const expressLogger = expressPino({
  autoLogging: {
    ignorePaths: ["/_next"],
    getPath: (req) => {
      if (/_next/.test(req.url)) {
        return "/_next"
      }
      return req.url
    }
  },
});
```
