### ISSUE TITLE
Hapi Event Description

### ISSUE THREAD

**Issue by felixheck** [pinojs/hapi-pino#31]
As far as I understand the current hapi v17 docs and the implementation of `hapi-pino`, its docs should be something like:

### Hapi Events

**hapi-pino** listens to some Hapi events:

* `'onRequest'`, to create a request-specific child logger
* `'response'`, to log at `'info'` level when a request is completed
* `'request'`, **to support logging via the Hapi `request.log()` method and to log at `'warn'` level when a request errors for `accept-encoding` tags, see `tags` and `allTags` options.**
* `'log'`, to support logging via the Hapi `server.log()` method ~and
  `request.log()` methods~ **and log in case of an internal server event**, see `tags` and `allTags` options.
* `'onPostStart'`, to log when the server is started
* `'onPostStop'`, to log when the server is stopped

**Comment by mcollina** [comment]
very likely. Would you mind to fire a PR?

**Comment by felixheck** [comment]
Yep, gonna push the PR in a few mins 👍
