### ISSUE TITLE
Handling of `request` logs on `app` level

### ISSUE THREAD

**Issue by felixheck** [pinojs/hapi-pino#33]
Currently the event listener for `request` just gets added if `request` is listed in `options.logEvents`. AFAIK in former versions of `hapi-pino` all `request.log()`/`server.log()` gets logged. 

So IMHO the `request` event should be registered anyway but the `event.error` part just if `request-error` is listed in `hapi-pino`.

**Comment by mcollina** [comment]
Sounds reasonable. Would you mind to fire a PR?

**Comment by felixheck** [comment]
Done!
