### ISSUE TITLE
Use Hapi Pino externally

### ISSUE THREAD

**Issue by microcipcip** [pinojs/hapi-pino#41]
I am correct to assume that if I need to use pino outside the server/request (in my case inside a mongo model) I need to import the main pino library directly?

**Comment by mcollina** [comment]
Either way is fine, but you should have a single instance of the logger itself.

I would recommend to initialize the persistence logic in its own Hapi plugin. From there, you can create a child of the server logger.

**Comment by microcipcip** [comment]
Ok, thanks a lot :)

P.S. I saw your talk about Pino, amazing job :)

**Comment by microcipcip** [comment]
Do I have to initialize a Pino log and pass it to the `[instance]` parameter? Could you provide a simple example of how I could achive this? Sorry, I am relatively new to Node

**Comment by davidmarkclements** [comment]
example in repo folder
