### ISSUE TITLE
prettyPrint does not work well with multiple servers

### ISSUE THREAD

**Issue by ferrao** [pinojs/hapi-pino#44]
I instantiate 3 different servers and register `hapi-pino` into all 3 with `prettyPrint=true`, but only the first server to register will have pretty logs.

**Comment by mcollina** [comment]
Would you like to send a PR to fix this?

**Comment by ferrao** [comment]
Sure thing, I can take a stab at it.

**Comment by ferrao** [comment]
Problem is this line : 

https://github.com/pinojs/hapi-pino/blob/8529345f330050302eb6b867b318a767dd604dcd/index.js#L36

Because I am registering the server multiple times with the same options object, after the first registration the original options object does not contain the `prettyPrint` flag enabled.

Its easy for me to supply a different options object on every registration, but I would argue that if the registration function alters the options object, then it should clone it internally to prevent this sort of problems, what do you think @mcollina ?

I have already made the necessary changes, but for some reason not obvious to me the tests are failing now. If you think this is the way to go I'll put in an extra effort to fix them :)

**Comment by felixheck** [comment]
Cloning the options object in case internal mutations seems legit in my point of view

**Comment by mcollina** [comment]
Feel free to send a PR.

**Comment by ferrao** [comment]
@mcollina can you shed some light on this black magic:

```javascript
function sink (func) {
  var result = split(JSON.parse)
  result.pipe(writeStream.obj(func))
  return result
}
```

**Comment by mcollina** [comment]
what do you not understand? It's node.js streams!

**Comment by ferrao** [comment]
The `split(JSON.parse)` expression confused me.

**Comment by mcollina** [comment]
It is this one: https://github.com/mcollina/split2#ndj---newline-delimited-json
