### ISSUE TITLE
Example Code

### ISSUE THREAD

**Issue by eppak** [pinojs/hapi-pino#52]
Hello,
i noticed that the example is not working for me, it register a require('.') but need require('hapi-pino'), i suppose that in the package it refer to itself so there is fine.

Is my assumption correct?
Thanks.

**Comment by davidmarkclements** [comment]
that's right - the example is intended to be run in the repo itself

this is a commonly occurring approach to `example.js` files

**Comment by geforcesong** [comment]
this is stupid documentation

**Comment by mcollina** [comment]
@geforcesong, I've censored your comment. Please be polite.
