### ISSUE TITLE
Disable logging for a specific route

### ISSUE THREAD

**Issue by devourment77** [pinojs/hapi-pino#54]
Knowing that hapi-pino will log responses at level info, what would the way to go about omitting a health check route from this (while keeping other responses still logging).

Thanks!

**Comment by mcollina** [comment]
This should help you: https://github.com/pinojs/hapi-pino/blob/master/index.js#L64-L68.

It's not documented, maybe would you mind to send a PR to document the option?

**Comment by devourment77** [comment]
Done! See https://github.com/pinojs/hapi-pino/pull/55

**Comment by mcollina** [comment]
Thanks!
