### ISSUE TITLE
Logging res body in 'response' event?

### ISSUE THREAD

**Issue by devourment77** [pinojs/hapi-pino#56]
I noticed that the response event is sending `res: request.raw.res` and while I do see the response status code and headers in the log, I do not see the response body content / json.

Is there a config option to enable this? Kind of surprised it was not included in request.raw.res.

Thanks!

**Comment by davidmarkclements** [comment]
You would need a custom, see the serializers option

Logging the body is not recommended from a performance perspective

**Comment by andreisoare** [comment]
How exactly could we enable logging the response body? This is useful at least for development (disabled in prod).

`res: request.raw.res` seems to be hardcoded and I can't figure out a way around that.

**Comment by mcollina** [comment]
As Dave said, you need to specify a custom serializer for res: http://getpino.io/#/docs/api?id=serializers-object. 

It would be awesome to get a PR to add this in the docs.
