### ISSUE TITLE
Just a question..

### ISSUE THREAD

**Issue by marianozunino** [pinojs/hapi-pino#57]
I would like to add some extra info to the request. It could be inside the request, o another key. Is it possible? I tried whith the following plugin, but then pino creates another log.

```
  register: async (server, options) => {
    server.events.on("response", (request, h) => {
      var re = new RegExp("^(/api/.).*");
      if (!re.test(request.url.pathname)) {
        request.logger.level = "silent";
      } else {
        server.log(["info"], { hello: "world" });
      }
    });
  },
```

```
[2018-05-07T18:23:46.991Z] INFO (15978 on Main): request completed
    req: {
      .....
    }
    payload: {
        ....
    }
    res: {
      ....
    }
    responseTime: 47

```

**Comment by felixheck** [comment]
I'd suggest to use a custom serializer for this purpose.

Further information in the docs of the plugin, of [pino](https://github.com/pinojs/pino/blob/master/docs/API.md#stdSerializers) and [pino-http](https://github.com/pinojs/pino-http)
