### ISSUE TITLE
Accept a min log level as an option

### ISSUE THREAD

**Issue by AndreasChristianson** [pinojs/hapi-pino#58]
By default Pino logs info level and higher messages. This can be changed via https://github.com/pinojs/pino/blob/master/docs/API.md#level

It would be convenient to pass in the minimum level as an option so that this doesn't have to be configured in a separate step. 

Possible api change:
```
  await server.register({
    plugin: require('hapi-pino'),
    options: {
      prettyPrint: process.env.NODE_ENV !== 'production',
      minLevel: 'debug'
    }
  });
```

**Comment by mcollina** [comment]
I think you should be able to pass `{ options: { level: 'debug' } }`. Is that not working?

**Comment by AndreasChristianson** [comment]
No, I haven't tried that. Will do! If it works I may send you a pr with a readme change

**Comment by AndreasChristianson** [comment]
Works great. I sent you a pr for the readme: https://github.com/pinojs/hapi-pino/pull/59
