### ISSUE TITLE
more pretty printing :)

### ISSUE THREAD

**Issue by jamesdixon** [pinojs/hapi-pino#6]
It's me again! lol...

Any thoughts on getting more pretty printing? This may be asking for too much and other tools may be able to help do the job, but curious if the whatever pretty printing method you're using has any option to color JSON output? ~~and stack traces? I actually gave @davidmarkclements `cute-stack` lib a try, but getting an error at the moment.~~ I love the console, but as you know, black + white doesn't always do it, especially with a lot of output.

Again, I am probably asking too much, but would love to hear your thoughts 👍 

Cheers,
James

**Comment by davidmarkclements** [comment]
Hey @jamesdixon cute-stack is for formatting stack traces, kind of a different thing. However feel free to open an issue on cure-stafk if can't resolve the error

One thing you could try, is passing the json through bunyan or bole CLI tools which also provide formatting - pino's JSON output is fairly consistent with both so I'm guessing it'll work

**Comment by jamesdixon** [comment]
@davidmarkclements yep, I'm aware :) Re-reading my statement above, it's a bit confusing. What I meant was that I was looking for something to get not only my logging, but stack traces formatted nicely as well -- hence trying your module for that the latter purpose. Sorry for the confusion!

**Comment by mcollina** [comment]
I think we can close this, but feel free to reopen in case.
