### ISSUE TITLE
Pretty print in 5.0.0 is broken

### ISSUE THREAD

**Issue by wraithgar** [pinojs/hapi-pino#61]
If I run with prettyPrint set to true I get an exception saying

```
TypeError: pino.pretty is not a function
    at Object.register ([...]node_modules/hapi-pino/index.js:47:25)
```

I don't think there are any tests actually testing prettyPrint, it's only used in a test that ensures the config object isn't being mutated.

**Comment by mcollina** [comment]
Thanks for catching this. Turns out we have a bug in pino, but a follow up will be needed here as well.

**Comment by mcollina** [comment]
See https://github.com/pinojs/pino/pull/474
