### ISSUE TITLE
Issue with overrideDefaultErrorSerializer

### ISSUE THREAD

**Issue by robmcguinness** [pinojs/hapi-pino#62]
When I pass an instance of `pino` into `hapi-pino` with custom serializers, the serializer lookup `logger[serializersSym].err` https://github.com/pinojs/hapi-pino/blob/master/index.js#L35 fails with **Cannot read property `err` of undefined**. It appears that if `options.instance` and `hapi-pino` use two separate dependencies of `pino` (possible in monorepo structure), the lookup fails because the symbols `Symbol('pino.serializers')` are different. 

Using `const serializersSym = Symbol.for('pino.serializers');` https://github.com/pinojs/pino/blob/master/lib/symbols.js#L13 resolves the lookup issue. 

I'll keep digging to see if I'm leveraging the framework incorrectly.

**Comment by mcollina** [comment]
You should use hapi-pino v4 with pino v4, and hapi-pino v5 with pino v5. I'll add some checks so that this is properly tested and error correctly.

**Comment by robmcguinness** [comment]
Hi @mcollina,

I noticed this issue after upgrading to `v5` of `pino` and `hapi-pino`.  I'll try and setup a sample monorepo replicating the issue.

**Comment by mcollina** [comment]
No need, I understand what’s the problem. I’ll release a fix later
today/tomorrow.
Il giorno mar 14 ago 2018 alle 13:46 robert mcguinness <
notifications@github.com> ha scritto:

**Comment by mcollina** [comment]
Should be fixed in pino v5.1.0. Update your dependencies and let me know.
