### ISSUE TITLE
response logEvents should honor ignorePaths

### ISSUE THREAD

**Issue by robmcguinness** [pinojs/hapi-pino#63]
It seems `ignorePaths` is only used when `logEvent` is `request` but would be beneficial when the log event is `response` as well. Like the **README** states, ignoring certain paths can reduce the noise in the logs for health check routes (Kubernetes pings a service quite frequently for health check routes).

If this sounds good I can submit a PR when time permits.

**Comment by mcollina** [comment]
Go for it!
Il giorno gio 16 ago 2018 alle 16:49 robert mcguinness <
notifications@github.com> ha scritto:
