### ISSUE TITLE
Support for hapi v18

### ISSUE THREAD

**Issue by hueniverse** [pinojs/hapi-pino#69]
https://github.com/pinojs/hapi-pino/blob/master/index.js#L118

`request.info.responded` is now only set for successful responses. `request.info.completed` is a new value that is always set. A backwards-compatible way to implement this is to use `completed` when available, otherwise `responded`.

In addition, changes to `request.url` might require other adjustments.

**Comment by mcollina** [comment]
I did some quick check, and our tests are 100% passing with Hapi v18 which is not that encouraging.

Can you please clarify what a "successful response" means in this context? Will the `'response'` event 
be fired for failed requests? 

(I'm sorry for the long delay, but I'm under an intense travel schedule)

**Comment by felixheck** [comment]
Adding/improving the tests has been on my agenda for months — but haven't had much time yet :/
But it's worth like we see in this case.

**Comment by hueniverse** [comment]
The `response` event always fires. No changes there. What changed is that when it is fired, if the request was closed/aborted by the client before the response was fully sent back, `request.info.responded` will  no longer be set. If you add a test for client disconnections, you will see the issue.

**Comment by felixheck** [comment]
Since #71 is merged and released as [`5.4.0`](https://github.com/pinojs/hapi-pino/releases/tag/v5.4.0), I'd close this issue.
