### ISSUE TITLE
PreHandler Usage

### ISSUE THREAD

**Issue by felixheck** [pinojs/hapi-pino#73]
Hi there 👋 

I was wondering how to utilize [prehandler](https://hapijs.com/api#route.options.pre) with `pino`/`hapi-pino`. Currently it's not possible because the `req` gets bound [too early](https://github.com/pinojs/hapi-pino/blob/master/index.js#L72-L79).

How's your opinion on a PR like one of those:

1. Check at [`onResponse`](https://github.com/pinojs/hapi-pino/blob/master/index.js#108) & [`req.log`](https://github.com/pinojs/hapi-pino/blob/master/index.js#L91) if `request.pre` is available; if so, re-init the logger.
2. Check at [`onRequest`](https://github.com/pinojs/hapi-pino/blob/master/index.js#L72) if there are prehandlers defined for the requested route; if so, skip logger initialisation. 

---

1. Seems to be quite inefficient because of the multiple initialisations
2. Really tricky bc the route and thus the config is not assigned at the time of `onRequest`. So we'd have to run `shot`/router which might be less efficient and hacky.

Any thoughts on this?

Cheers,
Felix

**Comment by mcollina** [comment]
Can you make an example of what you are trying to achieve?
