### ISSUE TITLE
Dependency warning on old version of hapi

### ISSUE THREAD

**Issue by mitra42** [pinojs/hapi-pino#82]
We are seeing a deprecation warning from hapi-pino which people including our package are complaining about :-)
```
warning @internetarchive/dweb-objects > @internetarchive/dweb-transports > ipfs > hapi-pino > @hapi/hoek@6.2.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
```

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by mitra42** [comment]
Out of my skill level - I've never touched your code so don't know if the dependency is intentional or not - our package is importing ipfs which is importing yours which is generating the warning, I'm happy to fix problems in ours but this is two levels deep in unknown code !

**Comment by mcollina** [comment]
@mitra42 I don't have a clue either on what was changed in hoek. I'm not directly using this module and I do not have this issue. Somebody should:

1. fork this repo
2. update that dep
3. check if tests are passing, and fix them if not
4. send a PR

There is always a first time for contributing to open source! :)

**Comment by mitra42** [comment]
Far from first time - got approx 16k lines in the packages I maintain on github, just not going to mess with someone else's package on something like this as I know how long it takes to get a working testing environment for anyone;s package !

**Comment by Akumzy** [comment]
I have created  a pull request [fixed](https://github.com/pinojs/hapi-pino/pull/83)

**Comment by mcollina** [comment]
This has been released.
