### ISSUE TITLE
Feature suggestion: add optional getChildBindings(request) to options instead of hardcoding .child({ req: request })

### ISSUE THREAD

**Issue by BlooJeans** [pinojs/hapi-pino#86]
Currently `hapi-pino` does
```javascript
server.ext('onRequest', (request, h) => {
  // ...
  request.logger = logger.child({
    req: request,
  })
//  ...
})
```
and
```javascript
  server.events.on('request', function (request, event, tags) {
    if (event.channel === 'internal' && !tags['accept-encoding']) {
      return
    }

    request.logger = request.logger || logger.child({
      req: request,
    })
```
which causes `req` to be included by default to _every_ call to pino.

My suggestion is to add an optional method to the hapi-pino options object, `getChildBindings(request)` (open to suggestions for a better name), which lets you customize the bindings attached to the child logger. The current behavior of automatically adding the `req` to the Pino child bindings can be kept by making that the default value for this new method.

i.e.
```typescript
getChildBindings?: (request: Hapi.Request) => Pino.Bindings = (req) => ({ req: req })
```

which will then be used instead of hardcoding `{ req: request }`:
```javascript
 // if getChildBindings defaults to the object
request.logger = logger.child(getChildBindings(request))
```
or
```javascript
// if getChildBindings defaults to undefined
const childBindings = getChildBindings ? getChildBindings(request) : { req: request };
request.logger = logger.child(childBindings)
```

If this suggestion sounds good, I'll be happy to make the PR.  Feedback welcome!

**Comment by mcollina** [comment]
Give it a shot and send a PR! Seems useful! I prefer the second implementation.
